---
# handlers file for install_nginx
 - name: restart if needed
   systemd:
      name: nginx
      state: restarted
      enabled: yes
   become: yes
   become_user: root

 - name: start daemon
   shell: systemctl start nginx
   become: yes
   become_user: root
