---
# tasks file for check_tomcat
  - name: chech availability
    shell: |
      curl -Is -K HEAD http://192.168.56.8:8080/ | head -n 1
      curl -Is -K HEAD http://192.168.56.12:8080/ | head -n 1
      curl -Is -K HEAD http://192.168.56.15:8080/ | head -n 1
    register: command_output

  - name: print result
    debug: 
        msg: "{{ command_output.stdout }}"
